import jsPDF from 'jspdf';
import type { Language } from '@/lib/i18n';
import type { ContractFormData, ContractType } from '@/components/contracts/ContractFormDialog';
import { TYPE_LABELS } from '@/components/contracts/ContractFormDialog';

const L = (language: Language) => ({
  title: language === 'fr' ? 'CONTRAT' : language === 'ar' ? 'CONTRAT' : 'CONTRACT',
  type: language === 'fr' ? 'Type' : language === 'ar' ? 'Type' : 'Type',
  subject: language === 'fr' ? 'Objet' : language === 'ar' ? 'Objet' : 'Subject',
  date: language === 'fr' ? 'Date' : 'Date',
  parties: language === 'fr' ? 'Parties' : language === 'ar' ? 'Parties' : 'Parties',
  delay: language === 'fr' ? "Délais d'exécution" : 'Execution delay',
  clauses: language === 'fr' ? 'Clauses' : 'Clauses',
  witnesses: language === 'fr' ? 'Témoins' : 'Witnesses',
  notes: language === 'fr' ? 'Notes' : 'Notes',
  signatures: language === 'fr' ? 'Signatures' : 'Signatures',
  generated: language === 'fr' ? 'Document généré par Hisab le' : language === 'ar' ? 'Document généré par Hisab le' : 'Document generated by Hisab on',
});

export function generateContractPdf(form: ContractFormData, language: Language) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const labels = L(language);
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensure = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const writeSection = (label: string, content: string | null | undefined) => {
    if (!content) return;
    ensure(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(60, 90, 70);
    doc.text(label.toUpperCase(), margin, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    const lines = doc.splitTextToSize(content, maxW);
    for (const line of lines) {
      ensure(6);
      doc.text(line, margin, y);
      y += 5;
    }
    y += 3;
  };

  // Header
  doc.setFillColor(46, 74, 58);
  doc.rect(0, 0, pageW, 28, 'F');
  doc.setTextColor(212, 175, 55);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(labels.title, pageW / 2, 14, { align: 'center' });
  doc.setFontSize(11);
  doc.setTextColor(240, 230, 200);
  doc.text(TYPE_LABELS[language][form.contract_type as ContractType] || form.contract_type, pageW / 2, 22, { align: 'center' });
  y = 38;

  // Title
  doc.setTextColor(30, 30, 30);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  const titleLines = doc.splitTextToSize(form.title || '-', maxW);
  for (const line of titleLines) {
    ensure(8);
    doc.text(line, margin, y);
    y += 7;
  }
  y += 2;

  if (form.contract_date) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`${labels.date}: ${form.contract_date}`, margin, y);
    y += 7;
  }

  // Separator
  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // Parties
  if (form.parties?.length) {
    ensure(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(60, 90, 70);
    doc.text(labels.parties.toUpperCase(), margin, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    form.parties.forEach((p, i) => {
      const txt = `${i + 1}. ${p.name || '-'}${p.role ? ` — ${p.role}` : ''}`;
      const lines = doc.splitTextToSize(txt, maxW);
      for (const line of lines) {
        ensure(6);
        doc.text(line, margin, y);
        y += 5;
      }
    });
    y += 3;
  }

  writeSection(labels.delay, form.execution_delay);
  writeSection(labels.clauses, form.clauses);

  // Witnesses
  if (form.witnesses?.length) {
    ensure(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(60, 90, 70);
    doc.text(labels.witnesses.toUpperCase(), margin, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    form.witnesses.forEach((w, i) => {
      const txt = `${i + 1}. ${w.name || '-'}${w.contact ? ` (${w.contact})` : ''}`;
      const lines = doc.splitTextToSize(txt, maxW);
      for (const line of lines) {
        ensure(6);
        doc.text(line, margin, y);
        y += 5;
      }
    });
    y += 3;
  }

  writeSection(labels.notes, form.notes);

  // Signatures
  ensure(40);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(60, 90, 70);
  doc.text(labels.signatures.toUpperCase(), margin, y);
  y += 10;
  doc.setDrawColor(120, 120, 120);
  doc.setLineWidth(0.2);
  const sigCount = Math.max(form.parties?.length || 0, 2);
  const colW = (maxW - (sigCount - 1) * 6) / sigCount;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  for (let i = 0; i < sigCount; i++) {
    const x = margin + i * (colW + 6);
    doc.line(x, y + 14, x + colW, y + 14);
    const name = form.parties?.[i]?.name || '';
    doc.text(name, x, y + 19);
  }
  y += 24;

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    doc.text(`${labels.generated} ${new Date().toLocaleDateString()}`, margin, pageH - 8);
    doc.text(`${i} / ${pageCount}`, pageW - margin, pageH - 8, { align: 'right' });
  }

  const safe = (form.title || 'contrat').replace(/[^a-z0-9-_]+/gi, '_').slice(0, 40);
  doc.save(`${safe}.pdf`);
}
